# jrsz.net parallel stack environment.
# Mirrors .env(.example) but targets the jrsz.net twin of every service.
# Published host ports differ from jrsz.org so both stacks run concurrently:
#   am.jrsz.net   -> host 9443 (AM also listens on 9443 inside the container)
#   ig.jrsz.net   -> host 8444 (gateway listens on 8443 inside the container)
AM_URL=https://am.jrsz.net:9443/am
AM_HTTPS_PORT=9443
AM_COOKIE_DOMAIN=jrsz.net
AM_ADMIN_PASSWORD=changeit
AM_KEYSTORE_PASSWORD=changeit
APP_KEYSTORE_PASSWORD=changeit
TRUSTSTORE_PASSWORD=changeit
DS_ROOT_PASSWORD=changeit
DS_MONITOR_PASSWORD=changeit
DS_AM_PROFILE_PASSWORD=changeit

# Demo realm end-user used by OAuth/OIDC smoke tests.
DEMO_USER_NAME=demo-user
DEMO_USER_PASSWORD='Jrsz$2025!'
IG_AGENT_ID=ig_agent_alpha
IG_AGENT_PASSWORD=igagent-changeit-01
IG_BASE_URL=https://ig.jrsz.net:8444
AM_REALM=/alpha
AM_REALM_PATH=realms/root/realms/alpha

# Public app base URLs (browser-facing, behind the jrsz.net gateway on 8444).
# Added to the alpha Validation Service validGotoDestinations.
PUBLIC_APP_BASE_URLS=https://app1.jrsz.net:8444 https://app2.jrsz.net:8444 https://app3.jrsz.net:8444 https://app4.jrsz.net:8444 https://app5.jrsz.net:8444 https://app6.jrsz.net:8444

# app4 PKCE demo overrides (jrsz.net).
APP4_BASE_URL=https://app4.jrsz.net:8444
APP4_OIDC_ISSUER_URL=https://am.jrsz.net:9443/am/oauth2/realms/root/realms/alpha
APP4_CLIENT_ID=demo-pkce-app
APP4_CLIENT_SECRET=

# Login Widget demo (app5) against AM /alpha on jrsz.net.
LOGIN_WIDGET_BASE_URL=https://app5.jrsz.net:8444
LOGIN_WIDGET_CLIENT_ID=sdkPublicClient
LOGIN_WIDGET_JOURNEY=sdkUsernamePasswordJourney
LOGIN_WIDGET_CORS_CONFIG_NAME=LoginWidget

# app6 session-timeout / logout / OIDC SLO test console (jrsz.net twin).
APP6_BASE_URL=https://app6.jrsz.net:8444
APP6_OIDC_ISSUER_URL=https://am.jrsz.net:9443/am/oauth2/realms/root/realms/timeout-test
TIMEOUT_REALM=/timeout-test
TIMEOUT_REALM_PATH=realms/root/realms/timeout-test
RP_C_CLIENT_ID=rp-c-app
RP_C_CLIENT_SECRET=rp-c-secret-changeit
RP_D_CLIENT_ID=rp-d-app
RP_D_CLIENT_SECRET=
AM_IDLE_MINUTES=6
AM_MAX_MINUTES=20
AT_TTL_SECONDS=300
RT_TTL_SECONDS=1800
ID_TTL_SECONDS=300
# timeout-test SSO session storage: true => client-side (stateless JWT) sessions,
# false => server-side (CTS) sessions. app6's "AM type" chip reflects this.
TIMEOUT_REALM_STATELESS=true
# Realm-local test user created in timeout-test by the bootstrap.
TIMEOUT_TEST_USER=tt-user
TIMEOUT_TEST_USER_PASSWORD=St@telessTest-2026-xyz

# Cross-AM OIDC social login (jrsz.org <-> jrsz.net). Secrets MUST match the
# jrsz.org stack (.env) so the OP client registration and consumer provider
# config agree. Base URLs are the same for both stacks (shared jrsz_net + ports).
ORG_AM_BASE_URL=https://am.jrsz.org:8443/am
COM_AM_BASE_URL=https://am.jrsz.net:9443/am
SOCIAL_ORG_RP_SECRET=org-social-secret-changeit
SOCIAL_COM_RP_SECRET=com-social-secret-changeit

# Amster one-shot bootstrap toggles (used by docker compose --profile bootstrap).
BOOTSTRAP_OAUTH2_DEMO_CONFIG=true
BOOTSTRAP_DEMO_USER=true
BOOTSTRAP_LOGIN_WIDGET_CONFIG=true
# Import the MFA / TOTP / Passkeys / Passwordless journeys into the alpha realm.
BOOTSTRAP_JOURNEYS=true
# Provision the cross-domain SAML federation and cross-AM social login.
BOOTSTRAP_SAML=true
BOOTSTRAP_SOCIAL=true

# Required mounts for the jrsz.net stack (generated by scripts/generate-tls.sh):
#   secrets/truststores/truststore.p12        (shared CA truststore)
#   secrets/tls/gateway-com/gateway.server.keypair.pem
#   secrets/tls/am-com/am-com.p12
#   secrets/tls/ds-com/keystore + keystore.pin
#   secrets/tls/app1-com/app1-com.p12 (and app2-com, app3-com)
#
# Host DNS or /etc/hosts must resolve these names to the Docker host:
#   am.jrsz.net ig.jrsz.net app1.jrsz.net app2.jrsz.net app3.jrsz.net
#   app4.jrsz.net app5.jrsz.net app6.jrsz.net

# Remote Connector Server (rcs.jrsz.net) -> bonaire05 AIC tenant. RCS_NAME must
# match the connector server registered in the tenant; the OAuth2 client
# (RCS_CLIENT_ID/SECRET, realm alpha, client_credentials, scope fr:idm:*) is
# created by scripts/provision_bonaire05_ldap_app.py from these same values.
RCS_URL=wss://openam-bonaire05.forgeblocks.com/openicf/0
RCS_NAME=jrsz-rcs
RCS_TOKEN_ENDPOINT=https://openam-bonaire05.forgeblocks.com:443/am/oauth2/realms/root/realms/alpha/access_token
RCS_CLIENT_ID=RCSjrsz-rcs
# RCS_CLIENT_SECRET is NOT stored here (.env.com is git-tracked): put it in secrets/rcs/client-secret
#   (mounted at /run/secrets/rcs; generated by scripts/provision_bonaire05_ldap_app.py if absent).
RCS_SCOPE=fr:idm:*
# LDAP connector (tenant side) -> ds.jrsz.net over LDAPS via the RCS.
RCS_LDAP_HOST=ds.jrsz.net
RCS_LDAP_PORT=1636
RCS_LDAP_BIND_DN=uid=am-identity-bind-account,ou=admins,ou=identities
RCS_LDAP_BIND_PASSWORD=changeit
RCS_LDAP_BASE_DN=ou=identities
RCS_LDAP_USERS_DN=ou=people,ou=identities
# Application / mapping ids in bonaire05.
BONAIRE_LDAP_APP_NAME=jrsz-ldap
# scripts/reset-stack.sh replays scripts/setup-ldap-onboarding.sh (seed users, RCS, tenant config).
BOOTSTRAP_LDAP_ONBOARDING=true
