AM_URL=https://am.jrsz.org:8443/am
AM_ADMIN_PWD=changeit
DEMO_REALM=/alpha
DEMO_REALM_PATH=realms/root/realms/alpha

APP4_BASE_URL=https://app4.jrsz.org
APP5_BASE_URL=https://app5.jrsz.org
APP6_BASE_URL=https://app6.jrsz.org

APP4_REDIRECT_URI=https://app4.jrsz.org/callback
APP5_REDIRECT_URI=https://app5.jrsz.org/callback
APP6_REDIRECT_URI=https://app6.jrsz.org/callback
